version: '3'
services:
  nest-schedule-demo:
    build: .
    container_name: nest-schedule-demo
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

